site_name: C2F4DT
site_description: Cloud2FEM for Digital Twins tools
site_author: Giovanni Castellazzi
repo_url: https://github.com/gcastellazzi/C2F4DT
theme:
  name: material
  logo: assets/logo-cloud2fem.png
  favicon: assets/logo-cloud2fem.png
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.sections
  - content.code.copy
  - content.action.edit
  - toc.integrate
markdown_extensions:
- admonition
- tables
- toc
- attr_list
- def_list
- pymdownx.highlight:
    anchor_linenums: true
    linenums: true
- pymdownx.superfences
- pymdownx.details
- pymdownx.tasklist
- toc:
    permalink: true
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
        - src
        options:
          docstring_style: google
          show_root_heading: true
          show_if_no_docstring: true
          show_source: true
          filters:
          - '!^_'
watch:
- src
nav:
- Home: 
  - C2F4DT: index.md
  - References: guide/reference.md
- Guide:
  - Overview: guide/overview.md
  - Installation: guide/installation.md
  - Architecture: guide/architecture.md
  - Code Tree: guide/code_tree.md
  - Flowchart: guide/flowchart.md
  - Gui Layout: guide/gui_layout.md
  - Plugins Developer Guide: guide/plugins_developer_guide.md
  - Console Guide: guide/console_guide.md
- Plugins:
  - Units: guide/plugins/units.md
  - Cloud metrics: guide/plugins/cloud_inspection.md
  - Transform RT: guide/plugins/transformations.md
  - VTK Import: guide/plugins/import_vtk.md
  - Cloud2FEM: guide/plugins/cloud2fem.md
- API Reference:
  - Index: api/index.md
  - c2f4dt: api/c2f4dt.md
  - c2f4dt.app: api/c2f4dt/app.md
  - c2f4dt.main_window: api/c2f4dt/main_window.md
  - c2f4dt.plugins: api/c2f4dt/plugins.md
  - c2f4dt.plugins.example_display_button: api/c2f4dt/plugins/example_display_button.md
  - c2f4dt.plugins.example_display_button.plugin: api/c2f4dt/plugins/example_display_button/plugin.md
  - c2f4dt.plugins.manager: api/c2f4dt/plugins/manager.md
  - c2f4dt.plugins.transform_rt: api/c2f4dt/plugins/transform_rt.md
  - c2f4dt.plugins.transform_rt.plugin: api/c2f4dt/plugins/transform_rt/plugin.md
  - c2f4dt.plugins.units: api/c2f4dt/plugins/units.md
  - c2f4dt.plugins.units.plugin: api/c2f4dt/plugins/units/plugin.md
  - c2f4dt.plugins.vtk_import: api/c2f4dt/plugins/vtk_import.md
  - c2f4dt.plugins.vtk_import.plugin: api/c2f4dt/plugins/vtk_import/plugin.md
  - c2f4dt.ui: api/c2f4dt/ui.md
  - c2f4dt.ui.console: api/c2f4dt/ui/console.md
  - c2f4dt.ui.display_panel: api/c2f4dt/ui/display_panel.md
  - c2f4dt.ui.import_summary_dialog: api/c2f4dt/ui/import_summary_dialog.md
  - c2f4dt.ui.viewer3d: api/c2f4dt/ui/viewer3d.md
  - c2f4dt.utils: api/c2f4dt/utils.md
  - c2f4dt.utils.icons: api/c2f4dt/utils/icons.md
  - c2f4dt.utils.io: api/c2f4dt/utils/io.md
  - c2f4dt.utils.io.importers: api/c2f4dt/utils/io/importers.md
  - c2f4dt.utils.systeminfo: api/c2f4dt/utils/systeminfo.md
  - c2f4dt.utils.theme: api/c2f4dt/utils/theme.md
