site_name: C2F4DT Docs
repo_url: https://github.com/gcastellazzi/C2F4DT

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - palette.toggle
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Specifications: specifications.md
  # The API section below is maintained by scripts/auto_api.py
  # It will be appended/overwritten on each run

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
  - attr_list
